USE master;  
GO  
CREATE DATABASE EvaluationChapter; 
USE EvaluationChapter;

CREATE TABLE DBO.CUE_PERSON(
	PK_CUE_PERSON INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	IDENTIFY INT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	GENER VARCHAR(25) NOT NULL,
	AGE INT, 
	DIRECTION VARCHAR(80),
	PHONE INT,
	PASSWORD VARCHAR(15),
	STATUS VARCHAR(10)
);

CREATE TABLE DBO.CUE_ACCOUNT(
	PK_CUE_ACCOUNT INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	ACCOUNT_TYPE VARCHAR(20) NOT NULL,
	ACCOUNT_NUMBER VARCHAR(50) NOT NULL,
	INITIAL_BALANCE VARCHAR(25) NOT NULL,
	ACCOUNT_STATUS INT, 
	PK_CUE_PERSON INT,
	CONSTRAINT FK_CUE_PERSON_CUE_ACCOUNT FOREIGN KEY (PK_CUE_PERSON)
	REFERENCES DBO.CUE_PERSON(PK_CUE_PERSON)
);

CREATE TABLE DBO.CUE_MOVEMENT(
	PK_CUE_MOVEMENT INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
	MOVEMENT_TYPE VARCHAR(20) NOT NULL,
	MOVEMENT_DATE DATE NOT NULL,
	MOVEMENT_VALUE DECIMAL,
	BALANCE DECIMAL, 
	PK_CUE_ACCOUNT INT,
	CONSTRAINT FK_CUE_ACCOUNT_CUE_MOVEMENT FOREIGN KEY (PK_CUE_ACCOUNT)
	REFERENCES DBO.CUE_ACCOUNT(PK_CUE_ACCOUNT)
);
